version: "3.7"

networks:
  consul-network:
    driver: bridge

services:
  consul-server:
    image: hashicorp/consul:1.15.1
    restart: always
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
      - ./consul/data.json:/data.json
      - consul_data:/consul/data
    networks:
      - consul-network
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    environment:
      - CONSUL_DATA_DIR=/consul/data
      - CONSUL_UID=502
      - CONSUL_GID=20
    command: "agent"    
    
  consul-client:
    depends_on:
      - consul-server
    image: hashicorp/consul:1.15.1
    restart: always
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
    networks:
      - consul-network
    command: "agent"

volumes:
  consul_data:
    driver: local
